<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-08T13:53:32-08:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Hat Cai',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1454484808,
        'latest_version' => '5.7.5.6',
        'do_page_reindex_check' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
);
